### ISSUE TITLE
APK Download?

### ISSUE THREAD

**Issue by IzzySoft** [codeka/weather#2]
Somehow the APK disappeared. Could you make it available again? Best would be attaching it to its corresponding tag (see [here](https://help.github.com/articles/creating-releases/) in the Github-docu when unsure what that means). Thanks in advance!

**Comment by codeka** [comment]
Unfortunately, I can't release an APK because the API key that weather underground requires is pretty expensive (definitely too expensive for me to pay for a free app). It used to be possible to sign up at weather underground for an API key as a developer and get like 100 free requests per day. But you'll have to compile from source yourself.

Sorry!

**Comment by IzzySoft** [comment]
That's bad news, @codeka :cry: The reason I'm asking is that I provided your app [with my repo](https://apt.izzysoft.de/fdroid/index/apk/au.com.codeka.weather), to make it easier for users to install and keep it up-to-date. Which I no longer can do then, unfortunately… (not being a dev, and not having a dev environment, compiling myself is not an option either).

Do you consider switching to a more open weather data provider?

**Comment by codeka** [comment]
Yeah, I filed #3 yesterday to do just that. No idea when that can happen unfortunately... (though there probably won't be any other updates to the app anyway, it basically works the way I want now)

**Comment by IzzySoft** [comment]
Thanks, that's good news! As for ETA: It's a hobby, so it's ready when you found time to implement it. I've subscibed there, too, so I'll can follow progress.

**Comment by IzzySoft** [comment]
No pressure, just checking: any news?
